# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0028_merge'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailimages', '0012_copy_image_permissions_to_collections'),
        ('cms', '0003_faction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='event',
        ),
        migrations.AddField(
            model_name='homepage',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.DeleteModel(
            name='EventPage',
        ),
        migrations.DeleteModel(
            name='Faction',
        ),
    ]
