# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_auto_20160106_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='cal.Slot'),
        ),
    ]
