# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_auto_20160124_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='faction',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='cal.Faction'),
            preserve_default=False,
        ),
    ]
