# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 19:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0008_auto_20160313_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cal.Faction'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL, verbose_name='użytkownik'),
        ),
    ]
