# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0010_faction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faction',
            old_name='user',
            new_name='users',
        ),
    ]
