# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0011_auto_20160313_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='otwarte'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ammo',
            field=models.TextField(blank=True, default='', verbose_name='amunicja'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='opis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='entry_fee',
            field=models.TextField(blank=True, default='', verbose_name='wpisowe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='fps',
            field=models.TextField(blank=True, default='', verbose_name='fps'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='info',
            field=models.TextField(blank=True, default='', verbose_name='wiecej informacji'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='rules',
            field=models.TextField(blank=True, default='', verbose_name='zasady gry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='terms',
            field=models.TextField(blank=True, default='', verbose_name='regulamin'),
            preserve_default=False,
        ),
    ]
