# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 11:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20151227_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message="Numer telefonu musi zostać wpisany w formacie: '+999999999'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
