# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 08:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160424_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message="Numer telefonu musi zostać wpisany w formacie: '+999999999'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='numer telefonu'),
        ),
    ]
